# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Use $ to prefix non public channels: ex: $private_chan', max_length=120, verbose_name='Name')),
                ('role', models.CharField(choices=[('public', 'Public'), ('users', 'Users'), ('staff', 'Staff'), ('superuser', 'Superuser')], max_length=20, verbose_name='Authorized for')),
                ('handler', models.TextField(blank=True, verbose_name='Javascript handler')),
                ('paths', models.CharField(blank=True, max_length=255, null=True, verbose_name='Connect from paths')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Channels',
                'verbose_name': 'Channel',
            },
        ),
    ]
