# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Use $ to prefix non public channels: ex: $private_chan', max_length=120, unique=True, verbose_name='Name')),
                ('role', models.CharField(choices=[('public', 'Public'), ('users', 'Users'), ('groups', 'Groups'), ('staff', 'Staff'), ('superuser', 'Superuser')], max_length=20, verbose_name='Authorized for')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('paths', models.CharField(blank=True, max_length=255, null=True, verbose_name='Connect from paths')),
                ('handler', models.TextField(blank=True, verbose_name='Javascript handler')),
                ('serializer', models.TextField(blank=True, verbose_name='Javascript serializer')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Groups')),
            ],
            options={
                'verbose_name_plural': 'Channels',
                'verbose_name': 'Channel',
            },
        ),
    ]
