# Generated by Django 4.0.1 on 2022-02-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='level',
            field=models.CharField(choices=[('public', 'Public'), ('users', 'Users'), ('groups', 'Groups'), ('staff', 'Staff'), ('superuser', 'Superuser')], default='superuser', max_length=20, verbose_name='Authorized for'),
        ),
    ]
