{% load instant_tags %}
publicChans: { {% get_channels_for_role '/' 'public' as chans %}{% for c in chans %}"{{c}}":{"msgs":0, "name":"{{c}}", "isActive":false, "receiving":false}{% if not forloop.last %},{% endif %}{% endfor %} },
usersChans: { {% get_channels_for_role '/' 'users' as chans %}{% for c in chans %}"{{c}}":{"msgs":0, "name":"{{c}}", "isActive":false, "receiving":false}{% if not forloop.last %},{% endif %}{% endfor %} },
staffChans: { {% get_channels_for_role '/' 'staff' as chans %}{% for c in chans %}"{{c}}":{"msgs":0, "name":"{{c}}", "isActive":false, "receiving":false}{% if not forloop.last %},{% endif %}{% endfor %} },
superuserChans: { {% get_channels_for_role '/' 'superuser' as chans %}{% for c in chans %}"{{c}}":{"msgs":0, "name":"{{c}}", "isActive":false, "receiving":false}{% if not forloop.last %},{% endif %}{% endfor %} },
formChan: "",
formMsg: "",
showForm: false,
receivingChanClass: "has-text-danger",
activeChanClass: "has-text-success",
publicChanClass: "fas fa-globe-asia",
usersChanClass: "fas fa-user",
staffChanClass: "fas fa-user-graduate",
superuserChanClass: "fas fa-cogs",
eventLabels: new Array,
msgClass: "",
formData: "",
labels: ['ok', 'info', 'important', 'debug', 'warning'],
timelineNumMsgs: new Array,
timeframeMsgs: 0,